[package]
name = "dynsym"
version = "0.1.0"
authors = ["oberien <jaro.fietz@gmx.de>"]

[dependencies]
object = { git = "https://github.com/oberien/object", rev = "3ae266f861129df4a610bbc067956314783b2f3e" }
cpp_demangle = "0.2.5"
memmap = "0.6.0"
