[package]
name = "refunct-tas-ingame-lib"
version = "0.1.0"
authors = ["oberien <jaro.fietz@gmx.de>"]

[dependencies]
lazy_static = "0.2.10"
byteorder = "1.0.0"
error-chain = "0.8.1"
memmap = "0.6.0"

[target.'cfg(unix)'.dependencies]
libc = "0.2.20"
object = { git = "https://github.com/oberien/object", rev = "3ae266f861129df4a610bbc067956314783b2f3e" }
cpp_demangle = "0.2.5"

[target.'cfg(windows)'.dependencies]
winapi = "0.2.8"
kernel32-sys = "0.2.2"

[target.'cfg(windows)'.build]
target = "i686-pc-windows-msvc"

[lib]
name = "rtil"
crate_type = ["dylib"]

[profile.dev]
panic = 'abort'

[profile.release]
debug = true
debug-assertions = true
panic = 'abort'