[package]
name = "refunct-tas"
version = "0.1.0"
authors = ["oberien <jaro.fietz@gmx.de>"]

[dependencies]
error-chain = "0.7.2"
toml = "0.2.1"
rustc-serialize = "0.3.22"
byteorder = "1.0.0"
hlua = "0.3"

[target.'cfg(windows)'.dependencies]
winapi = "0.2.8"
kernel32-sys = "0.2.2"
